return {
  ["workshop-1079538195"]={
    configuration_options={
      beebox=true,
      birdcage=true,
      cartographydesk=true,
      cookpot=true,
      dragonflychest=true,
      dragonflyfurnace=true,
      endtable=true,
      firesuppressor=true,
      icebox=true,
      lightning_rod=true,
      meatrack=true,
      modsupport=true,
      moondial=true,
      mushroom_farm=true,
      mushroom_light=true,
      nightlight=true,
      perdshrine=true,
      pottedfern=true,
      rainometer=true,
      researchlab=true,
      researchlab2=true,
      researchlab3=true,
      researchlab4=true,
      resurrectionstatue=true,
      saltlick=true,
      scarecrow=true,
      sculptingtable=true,
      succulent_potted=true,
      townportal=true,
      treasurechest=true,
      wardrobe=true,
      winterometer=true 
    },
    enabled=true 
  },
  ["workshop-1207269058"]={ configuration_options={  }, enabled=true },
  ["workshop-1271089343"]={
    configuration_options={ bekkitt_skeleton_pen=0, null_option=true, skeleton_player=true },
    enabled=true 
  },
  ["workshop-1898292532"]={
    configuration_options={
      antlion=true,
      atrium_gate=false,
      bearger=true,
      beequeenhive=false,
      crabking=false,
      deerclops=true,
      dragonfly=false,
      hound=true,
      klaus_sack=false,
      malbatross=false,
      tips_method=1,
      toadstool=false 
    },
    enabled=true 
  },
  ["workshop-1909182187"]={
    configuration_options={
      all_containerdrag_switch=true,
      containerdrag_switch="KEY_F1",
      difficulty_switch=true,
      language_switch="ch",
      medal_goodmax_resources_multiple=0,
      medal_goodmid_resources_multiple=0,
      medal_info_switch=true,
      medal_inv_switch=true,
      medal_new_crafttabs_switch=true,
      medal_tips_switch=true,
      medalequipslots_switch=true,
      medalpage_switch=false,
      show_medal_fx=true,
      transplant_switch=true 
    },
    enabled=true 
  },
  ["workshop-1991746508"]={ configuration_options={ Language="CHINESE", ShowBuff=true }, enabled=true },
  ["workshop-2420839895"]={
    configuration_options={
      ROPE_BRIDGE_BOARDS_RATIO=0.25,
      ROPE_BRIDGE_DISTANCE=16,
      ROPE_BRIDGE_ROPE_RATIO=0.25 
    },
    enabled=true 
  },
  ["workshop-356930882"]={
    configuration_options={ uses=10000000, uses2=10000000, uses3=10000000 },
    enabled=true 
  },
  ["workshop-362175979"]={ configuration_options={ ["Draw over FoW"]="enabled" }, enabled=true },
  ["workshop-375850593"]={ configuration_options={  }, enabled=true },
  ["workshop-466732225"]={ configuration_options={  }, enabled=true },
  ["workshop-661253977"]={
    configuration_options={ amudiao=true, baodiao=1, kong=0, nillots=0, rendiao=2, zbdiao=true },
    enabled=true 
  },
  ["workshop-666155465"]={
    configuration_options={
      chestB=-1,
      chestG=-1,
      chestR=-1,
      display_hp=-1,
      food_estimation=-1,
      food_order=1,
      food_style=1,
      lang="chs",
      show_food_units=-1,
      show_uses=-1 
    },
    enabled=true 
  } 
}